#general information

string station
string dist

#current weather info(oberservation)

string obs_dt
uint32 obs_t
uint32 obs_tf
string obs_s
string obs_wn
uint32 obs_ws
float64 obs_p
uint32 obs_rh
uint32 obs_v

#frocast wearher info(fc)

string fc_dt
string fc_s
uint32 fc_tx
uint32 fc_tn
float64 fc_pr
string fc_wsx
uint32 fc_cloudiness
string fc_sunrise
string fc_sunset
string fc_sr